language: php

sudo: false

os:
  - linux

env:
  global:
    - PHP_COMPOSER_SETUP=basic
    - PHP_CS_FIXER_IGNORE=false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env:
        - PHP_CS_FIXER_IGNORE=true
    - php: 7.3
      env:
        - PHP_COMPOSER_SETUP=lowest
        - PHP_CS_FIXER_IGNORE=true
    - php: nightly

before_script:
  - stty cols 120
  - php --version
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls
  - travis_retry composer require phpstan/phpstan-shim
  - if [[ $PHP_CS_FIXER_IGNORE = false ]]; then travis_retry composer require friendsofphp/php-cs-fixer; fi
  - if [[ $PHP_COMPOSER_SETUP = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $PHP_COMPOSER_SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --debug
  - php vendor/bin/phpstan analyse --level=5 --configuration=phpstan.neon src

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
